#!/bin/sh

. /Applications/wordpress-4.8.php56-0/scripts/setenv.sh
SASL_PATH="/Applications/wordpress-4.8.php56-0/common/lib/sasl2"
                export SASL_PATH
exec /Applications/wordpress-4.8.php56-0/common/sbin/.saslpasswd2.bin -f "/Applications/wordpress-4.8.php56-0/common/etc/sasldb2" "$@"
